[tool.poetry]
name = "livy"
version = "0.3.2"
description = "Library to interact with Apache livy"
authors = ["tzing <tzingshih@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
dataclasses = {version = "^0.6", python = "<3.7"}
colorlog = {version = "^6.4.1", optional = true}

[tool.poetry.dev-dependencies]
black = "^21.7b0"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"

[tool.poetry.extras]
pretty = ["colorlog"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov=livy --cov-report=term-missing"

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if typing.TYPE_CHECKING"
]
