name: Build documents

on:
  push:
    branches:
      - trunk
  pull_request: {} # TODO remove

jobs:
  sphinx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install --no-root --extras pretty --extras aws

      - name: Build doc
        run: |
          poetry run sphinx-build -b html docs build

      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
